//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keyword
    {
        public Keyword()
        {
            this.WebsiteKeywords = new HashSet<WebsiteKeyword>();
        }
    
        public int ID { get; set; }
        public string Keyword1 { get; set; }
    
        public virtual ICollection<WebsiteKeyword> WebsiteKeywords { get; set; }
    }
}
