//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tweet
    {
        public Tweet()
        {
            this.TweetHashtags = new HashSet<TweetHashtag>();
            this.TweetWebsites = new HashSet<TweetWebsite>();
            this.Websites = new HashSet<Website>();
        }
    
        public int ID { get; set; }
        public string TweetID { get; set; }
        public System.DateTime Date { get; set; }
        public string Username { get; set; }
        public string TweetText { get; set; }
    
        public virtual ICollection<TweetHashtag> TweetHashtags { get; set; }
        public virtual ICollection<TweetWebsite> TweetWebsites { get; set; }
        public virtual ICollection<Website> Websites { get; set; }
    }
}
