//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TweetWebsite
    {
        public int ID { get; set; }
        public int TweetID { get; set; }
        public int WebsiteID { get; set; }
    
        public virtual Tweet Tweet { get; set; }
        public virtual Website Website { get; set; }
    }
}
