//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Website
    {
        public Website()
        {
            this.Media = new HashSet<Medium>();
            this.TweetWebsites = new HashSet<TweetWebsite>();
            this.WebsiteKeywords = new HashSet<WebsiteKeyword>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public int HitCount { get; set; }
        public int TweetID { get; set; }
        public string LongUrlTitle { get; set; }
        public string Description { get; set; }
        public string DisplayUrl { get; set; }
    
        public virtual ICollection<Medium> Media { get; set; }
        public virtual Tweet Tweet { get; set; }
        public virtual ICollection<TweetWebsite> TweetWebsites { get; set; }
        public virtual ICollection<WebsiteKeyword> WebsiteKeywords { get; set; }
    }
}
